# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.BooleanField(default=False, verbose_name='\u89d2\u8272'),
        ),
    ]
