# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reallyname',
            field=models.CharField(default='\u672a\u547d\u540d', max_length=150, null=True, verbose_name='\u771f\u5b9e\u59d3\u540d'),
        ),
    ]
