# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_reallyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reallyname',
            field=models.CharField(default='\u672a\u547d\u540d', max_length=32, null=True, verbose_name='\u771f\u5b9e\u59d3\u540d'),
        ),
    ]
