# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import taskpackages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'error': '\u4efb\u52a1\u5305\u540d\u5b57\u5df2\u5b58\u5728'}, max_length=150, unique=True, verbose_name='\u4efb\u52a1\u5305\u540d\u79f0')),
                ('owner', models.CharField(max_length=150, null=True, verbose_name='\u4e3b\u7248\u672c\u4f5c\u4e1a\u5458')),
                ('exowner', models.CharField(max_length=150, null=True, verbose_name='\u524d\u4f5c\u4e1a\u5458')),
                ('mapnums', models.CharField(max_length=65536, null=True, verbose_name='\u56fe\u53f7')),
                ('file', models.FileField(null=True, upload_to=taskpackages.models.user_directory_path, verbose_name='\u4efb\u52a1\u5305\u6587\u4ef6')),
                ('status', models.CharField(default='0', max_length=10, verbose_name='\u4efb\u52a1\u5305\u72b6\u6001')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('describe', models.CharField(max_length=200, null=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
                ('isdelete', models.BooleanField(default=False, verbose_name='\u903b\u8f91\u5220\u9664')),
            ],
            options={
                'verbose_name': '\u4efb\u52a1\u5305',
                'verbose_name_plural': '\u4efb\u52a1\u5305',
            },
        ),
        migrations.CreateModel(
            name='TaskPackageOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskpackage_name', models.CharField(max_length=150, null=True, verbose_name='\u4e3b\u4efb\u52a1\u5305\u540d\u79f0')),
                ('owner', models.CharField(max_length=150, verbose_name='\u4f5c\u4e1a\u5458')),
                ('exowner', models.CharField(blank=True, max_length=150, null=True, verbose_name='\u524d\u4f5c\u4e1a\u5458')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('describe', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6587\u4ef6\u63cf\u8ff0')),
                ('isdelete', models.BooleanField(default=False, verbose_name='\u903b\u8f91\u5220\u9664')),
            ],
            options={
                'verbose_name': '\u4efb\u52a1\u5305\u5f52\u5c5e',
                'verbose_name_plural': '\u4efb\u52a1\u5305\u5f52\u5c5e',
            },
        ),
        migrations.CreateModel(
            name='TaskPackageSon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskpackage_name', models.CharField(max_length=150, null=True, verbose_name='\u4e3b\u4efb\u52a1\u5305\u540d\u79f0')),
                ('version', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5b50\u4efb\u52a1\u5305\u7248\u672c\u53f7')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('describe', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
                ('file', models.FileField(blank=True, null=True, upload_to=taskpackages.models.user_directory_path, verbose_name='\u4efb\u52a1\u5305\u6587\u4ef6')),
                ('user_username', models.CharField(max_length=150, null=True, verbose_name='\u4f5c\u4e1a\u5458')),
                ('isdelete', models.BooleanField(default=False, verbose_name='\u903b\u8f91\u5220\u9664')),
            ],
            options={
                'verbose_name': '\u5b50\u4efb\u52a1\u5305',
                'verbose_name_plural': '\u5b50\u4efb\u52a1\u5305',
            },
        ),
    ]
