# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taskpackages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpackage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskpackage', to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u4e1a\u5458'),
        ),
    ]
