# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-22 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpackage',
            name='mapnumcounts',
            field=models.IntegerField(default=0, verbose_name='\u56fe\u5e45\u6570'),
        ),
        migrations.AlterField(
            model_name='taskpackage',
            name='describe',
            field=models.CharField(max_length=1000, null=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='taskpackage',
            name='mapnums',
            field=models.CharField(max_length=65536, null=True, verbose_name='\u56fe\u53f7\u96c6'),
        ),
        migrations.AlterField(
            model_name='taskpackage',
            name='name',
            field=models.CharField(error_messages={'unique': '\u4efb\u52a1\u5305\u540d\u79f0\u5df2\u5b58\u5728'}, max_length=150, unique=True, verbose_name='\u4efb\u52a1\u5305\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='taskpackageson',
            name='describe',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f'),
        ),
    ]
