# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0002_auto_20190107_1430'),
    ]

    operations = [
        # migrations.RenameModel(
        #     old_name='Schedule',
        #     new_name='TaskPackageScheduleSet',
        # ),
    ]
