# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-22 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0002_auto_20181222_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpackageson',
            name='schedule',
            field=models.CharField(choices=[('\u672a\u6307\u5b9a\u72b6\u6001', '\u672a\u6307\u5b9a\u72b6\u6001'), ('\u4fee\u6539\u7f1d\u9699', '\u4fee\u6539\u7f1d\u9699'), ('\u6cb3\u7f51\u73af\u4fee\u6539', '\u6cb3\u7f51\u73af\u4fee\u6539'), ('\u6709\u5411\u70b9\u4fee\u6539', '\u6709\u5411\u70b9\u4fee\u6539'), ('\u4e00\u5bf9\u591a\u4fee\u6539', '\u4e00\u5bf9\u591a\u4fee\u6539'), ('\u531d\u9053\u8d4b\u503c', '\u531d\u9053\u8d4b\u503c'), ('\u540c\u5c42\u62d3\u6251', '\u540c\u5c42\u62d3\u6251'), ('\u4e0d\u540c\u5c42\u62d3\u6251', '\u4e0d\u540c\u5c42\u62d3\u6251'), ('\u5fae\u77ed\u7ebf\u4fee\u6539', '\u5fae\u77ed\u7ebf\u4fee\u6539'), ('\u5fae\u5c0f\u9762\u4fee\u6539', '\u5fae\u5c0f\u9762\u4fee\u6539'), ('\u6025\u9510\u89d2\u4fee\u6539', '\u6025\u9510\u89d2\u4fee\u6539'), ('\u7b49\u9ad8\u7ebf\u62fc\u63a5', '\u7b49\u9ad8\u7ebf\u62fc\u63a5')], default='\u672a\u6307\u5b9a\u72b6\u6001', max_length=32),
        ),
    ]
