# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import taskpackages.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0003_auto_20190107_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPackageChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='\u6587\u4ef6\u5207\u7247')),
                ('file_chunk', models.FileField(null=True, upload_to=taskpackages.models.file_chunk_path, verbose_name='\u6587\u4ef6\u5207\u7247')),
                ('chunk', models.IntegerField(null=True, verbose_name='\u7b2c\u51e0\u4e2a')),
                ('chunks', models.IntegerField(null=True, verbose_name='\u5171\u7b2c\u51e0\u4e2a')),
                ('file_md5', models.CharField(max_length=128, null=True, verbose_name='MD5')),
                ('chunk_md5', models.CharField(max_length=128, null=True, verbose_name='\u6587\u4ef6\u5207\u5757md5')),
                ('file_name', models.CharField(max_length=32, null=True, verbose_name='\u6587\u4ef6\u771f\u5b9e\u59d3\u540d')),
            ],
            options={
                'verbose_name': '\u6587\u4ef6\u5207\u7247',
                'verbose_name_plural': '\u6587\u4ef6\u5207\u7247',
            },
        ),
    ]
