# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0003_auto_20181204_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpackageversion',
            name='version',
            field=models.CharField(default='v1.0', max_length=128, verbose_name='\u7248\u672c\u53f7'),
        ),
    ]
