# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0004_auto_20190114_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpackage',
            name='regiontask_name',
            field=models.CharField(default='\u4e1c\u5357\u533a\u57df', max_length=150, null=True, verbose_name='\u4e3b\u7248\u672c\u4f5c\u4e1a\u5458'),
        ),
        migrations.AddField(
            model_name='taskpackageowner',
            name='regiontask_name',
            field=models.CharField(default='\u4e1c\u5357\u533a\u57df', max_length=150, null=True, verbose_name='\u4e3b\u7248\u672c\u4f5c\u4e1a\u5458'),
        ),
        migrations.AddField(
            model_name='taskpackageson',
            name='regiontask_name',
            field=models.CharField(default='\u4e1c\u5357\u533a\u57df', max_length=150, null=True, verbose_name='\u4e3b\u7248\u672c\u4f5c\u4e1a\u5458'),
        ),
    ]
