# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0004_auto_20181204_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpackageversion',
            name='version',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7248\u672c\u53f7'),
        ),
    ]
