# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0005_auto_20190111_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskPackageSonMerge',
        ),
        migrations.AddField(
            model_name='taskpackageson',
            name='md5',
            field=models.CharField(max_length=128, null=True, verbose_name='MD5'),
        ),
    ]
