# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0005_auto_20181205_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskpackageversion',
            old_name='version',
            new_name='version_name',
        ),
    ]
