# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-25 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0005_auto_20181222_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpackage',
            name='mapnumcounts',
            field=models.IntegerField(default=0, null=True, verbose_name='\u56fe\u5e45\u6570'),
        ),
    ]
