# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0005_auto_20190114_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='echartschedule',
            name='regiontask_name',
            field=models.CharField(default='\u4e1c\u5357\u533a\u57df', max_length=150, null=True, verbose_name='\u4e3b\u7248\u672c\u4f5c\u4e1a\u5458'),
        ),
        migrations.AddField(
            model_name='echarttaskpackage',
            name='regiontask_name',
            field=models.CharField(default='\u4e1c\u5357\u533a\u57df', max_length=150, null=True, verbose_name='\u4e3b\u7248\u672c\u4f5c\u4e1a\u5458'),
        ),
        migrations.AlterField(
            model_name='regiontask',
            name='name',
            field=models.CharField(error_messages={'unique': '\u4efb\u52a1\u5305\u533a\u57df\u5df2\u5b58\u5728'}, max_length=200, null=True, unique=True, verbose_name='\u4efb\u52a1\u533a\u57df'),
        ),
    ]
