# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-25 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0006_auto_20181225_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpackage',
            name='schedule',
            field=models.CharField(default='\u672a\u6307\u5b9a\u72b6\u6001', max_length=32, null=True, verbose_name='\u4efb\u52a1\u5305\u8fdb\u5ea6'),
        ),
    ]
