# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0006_auto_20190114_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echartschedule',
            name='taskpackage_schedule',
            field=models.CharField(max_length=150, null=True, verbose_name='\u4efb\u52a1\u5305\u5904\u7406\u8fdb\u5ea6'),
        ),
        migrations.AlterField(
            model_name='echarttaskpackage',
            name='user_reallyname',
            field=models.CharField(max_length=150, null=True, verbose_name='\u4f5c\u4e1a\u5458'),
        ),
    ]
