# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0007_auto_20190114_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpackagescheduleset',
            name='regiontask_name',
            field=models.CharField(default='\u4e1c\u5357\u533a\u57df', max_length=150, verbose_name='\u4efb\u52a1\u533a\u57df'),
        ),
        migrations.AlterField(
            model_name='echartschedule',
            name='regiontask_name',
            field=models.CharField(default='\u4e1c\u5357\u533a\u57df', max_length=150, verbose_name='\u4efb\u52a1\u533a\u57df'),
        ),
        migrations.AlterField(
            model_name='echarttaskpackage',
            name='regiontask_name',
            field=models.CharField(default='\u4e1c\u5357\u533a\u57df', max_length=150, verbose_name='\u4efb\u52a1\u533a\u57df'),
        ),
        migrations.AlterField(
            model_name='taskpackage',
            name='regiontask_name',
            field=models.CharField(default='\u4e1c\u5357\u533a\u57df', max_length=150, verbose_name='\u4efb\u52a1\u533a\u57df'),
        ),
        migrations.AlterField(
            model_name='taskpackageowner',
            name='regiontask_name',
            field=models.CharField(default='\u4e1c\u5357\u533a\u57df', max_length=150, verbose_name='\u4efb\u52a1\u533a\u57df'),
        ),
        migrations.AlterField(
            model_name='taskpackageson',
            name='regiontask_name',
            field=models.CharField(default='\u4e1c\u5357\u533a\u57df', max_length=150, verbose_name='\u4efb\u52a1\u533a\u57df'),
        ),
    ]
