# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-26 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0007_auto_20181225_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpackage',
            name='newtaskpackagesonfornotice',
            field=models.IntegerField(default=0, null=True, verbose_name='\u6d88\u606f\u63d0\u9192'),
        ),
    ]
