# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0008_auto_20190114_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpackage',
            name='name',
            field=models.CharField(max_length=150, verbose_name='\u4efb\u52a1\u5305\u540d\u79f0'),
        ),
    ]
