# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-04 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0009_auto_20181229_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='EchartSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskpackage_schedule', models.CharField(max_length=150, null=True, unique=True, verbose_name='\u4efb\u52a1\u5305\u5904\u7406\u8fdb\u5ea6')),
                ('count', models.IntegerField(default=0, null=True, verbose_name='\u4efb\u52a1\u5305\u6570\u91cf')),
            ],
        ),
        migrations.CreateModel(
            name='EchartTaskPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=150, null=True, unique=True, verbose_name='\u4f5c\u4e1a\u5458')),
                ('count', models.IntegerField(default=0, null=True, verbose_name='\u4efb\u52a1\u5305\u6570\u91cf')),
            ],
        ),
        migrations.AlterField(
            model_name='taskpackage',
            name='reallyname',
            field=models.CharField(default=None, max_length=150, null=True, verbose_name='\u4f5c\u4e1a\u5458\u771f\u5b9e\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='taskpackageson',
            name='schedule',
            field=models.IntegerField(choices=[(0, '\u672a\u6307\u5b9a\u72b6\u6001'), (1, '\u4fee\u6539\u7f1d\u9699'), (2, '\u6cb3\u7f51\u73af\u4fee\u6539'), (3, '\u6709\u5411\u70b9\u4fee\u6539'), (4, '\u4e00\u5bf9\u591a\u4fee\u6539'), (5, '\u531d\u9053\u8d4b\u503c'), (6, '\u540c\u5c42\u62d3\u6251'), (7, '\u4e0d\u540c\u5c42\u62d3\u6251'), (8, '\u5fae\u77ed\u7ebf\u4fee\u6539'), (9, '\u5fae\u5c0f\u9762\u4fee\u6539'), (10, '\u6025\u9510\u89d2\u4fee\u6539'), (11, '\u7b49\u9ad8\u7ebf\u62fc\u63a5'), (12, '\u5df2\u5b8c\u6210')], default=0, verbose_name='\u4efb\u52a1\u5305\u8fdb\u5ea6'),
        ),
    ]
