# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0009_auto_20190114_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiontask',
            name='status',
            field=models.CharField(default='\u5904\u7406\u4e2d', max_length=200, verbose_name='\u72b6\u6001'),
        ),
    ]
