# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0010_regiontask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echarttaskpackage',
            name='user_reallyname',
            field=models.CharField(max_length=200, null=True, verbose_name='\u4f5c\u4e1a\u5458'),
        ),
        migrations.AlterField(
            model_name='taskpackage',
            name='schedule',
            field=models.CharField(default='\u672a\u6307\u5b9a\u72b6\u6001', max_length=200, verbose_name='\u4efb\u52a1\u5305\u5904\u7406\u8fdb\u5ea6'),
        ),
        migrations.AlterField(
            model_name='taskpackage',
            name='status',
            field=models.CharField(default='0', max_length=100, verbose_name='\u4efb\u52a1\u5305\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='taskpackageowner',
            name='describe',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u6587\u4ef6\u63cf\u8ff0'),
        ),
    ]
