# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-19 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0013_auto_20190118_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiontask',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='regiontask',
            name='describe',
            field=models.CharField(max_length=2000, null=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f'),
        ),
    ]
