# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-23 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import taskpackages.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0014_auto_20190119_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPackageChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskpackage_name', models.CharField(error_messages={'unique': '\u4efb\u52a1\u5305\u540d\u79f0\u5df2\u5b58\u5728'}, max_length=150, unique=True, verbose_name='\u6587\u4ef6\u5207\u7247')),
                ('file_chunk', models.FileField(null=True, upload_to=taskpackages.models.file_chunk_path, verbose_name='\u6587\u4ef6\u5207\u7247')),
                ('chunk', models.IntegerField(null=True, verbose_name='\u7b2c\u51e0\u4e2a')),
                ('chunks', models.IntegerField(null=True, verbose_name='\u5171\u7b2c\u51e0\u4e2a')),
                ('file_md5', models.CharField(max_length=128, null=True, verbose_name='MD5')),
                ('chunk_md5', models.CharField(max_length=128, null=True, verbose_name='\u6587\u4ef6\u5207\u5757md5')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6587\u4ef6\u5207\u7247',
                'verbose_name_plural': '\u6587\u4ef6\u5207\u7247',
            },
        ),
        migrations.CreateModel(
            name='TaskPackageSonMerge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=taskpackages.models.file_chunk_path, verbose_name='\u6587\u4ef6\u5207\u7247')),
                ('taskpackage_name', models.CharField(max_length=150, null=True, verbose_name='\u4e3b\u4efb\u52a1\u5305\u540d\u79f0')),
                ('user_username', models.CharField(max_length=150, null=True, verbose_name='\u4f5c\u4e1a\u5458')),
                ('version', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5b50\u4efb\u52a1\u5305\u7248\u672c\u53f7')),
                ('describe', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('schedule', models.CharField(default='\u672a\u6307\u5b9a\u72b6\u6001', max_length=32, verbose_name='\u4efb\u52a1\u5305\u8fdb\u5ea6')),
                ('md5', models.CharField(max_length=32, null=True, verbose_name='\u6587\u4ef6MD5')),
            ],
            options={
                'verbose_name': '\u5b50\u4efb\u52a1\u5305\u5408\u5e76',
                'verbose_name_plural': '\u5b50\u4efb\u52a1\u5305\u5408\u5e76',
            },
        ),
        migrations.AddField(
            model_name='taskpackageson',
            name='md5',
            field=models.CharField(max_length=32, null=True, verbose_name='\u6587\u4ef6MD5'),
        ),
    ]
