# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-13 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0017_auto_20190213_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regiontaskchunk',
            old_name='chunk_md5',
            new_name='chunkmd5',
        ),
        migrations.RenameField(
            model_name='regiontaskchunk',
            old_name='file_md5',
            new_name='filemd5',
        ),
        migrations.RemoveField(
            model_name='regiontaskchunk',
            name='basemapservice',
        ),
        migrations.RemoveField(
            model_name='regiontaskchunk',
            name='describe',
        ),
        migrations.RemoveField(
            model_name='regiontaskchunk',
            name='mapindexfeatureservice',
        ),
        migrations.RemoveField(
            model_name='regiontaskchunk',
            name='mapindexmapservice',
        ),
        migrations.RemoveField(
            model_name='regiontaskchunk',
            name='mapindexschedulemapservice',
        ),
        migrations.RemoveField(
            model_name='regiontaskchunk',
            name='mapindexsde',
        ),
        migrations.RemoveField(
            model_name='regiontaskchunk',
            name='rgssde',
        ),
        migrations.RemoveField(
            model_name='regiontaskchunk',
            name='status',
        ),
        migrations.RemoveField(
            model_name='regiontaskmerge',
            name='basemapservice',
        ),
        migrations.RemoveField(
            model_name='regiontaskmerge',
            name='describe',
        ),
        migrations.RemoveField(
            model_name='regiontaskmerge',
            name='mapindexfeatureservice',
        ),
        migrations.RemoveField(
            model_name='regiontaskmerge',
            name='mapindexmapservice',
        ),
        migrations.RemoveField(
            model_name='regiontaskmerge',
            name='mapindexschedulemapservice',
        ),
        migrations.RemoveField(
            model_name='regiontaskmerge',
            name='mapindexsde',
        ),
        migrations.RemoveField(
            model_name='regiontaskmerge',
            name='rgssde',
        ),
        migrations.RemoveField(
            model_name='regiontaskmerge',
            name='status',
        ),
    ]
