# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-14 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0019_auto_20190213_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiontaskchunk',
            name='status',
            field=models.CharField(default='\u672a\u6821\u9a8c', max_length=128, verbose_name='\u6821\u9a8c\u662f\u5426\u6210\u529f'),
        ),
    ]
