# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-15 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0020_regiontaskchunk_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiontask',
            name='servicename',
            field=models.CharField(error_messages={'unique': '\u4efb\u52a1\u533a\u57df\u5df2\u5b58\u5728'}, max_length=64, null=True, unique=True, verbose_name='\u670d\u52a1\u540d\u79f0'),
        ),
    ]
