# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-19 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0021_regiontask_servicename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiontask',
            name='servicename',
        ),
    ]
