# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-27 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0024_auto_20190222_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpackage',
            name='taskuuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, null=True, verbose_name='uuid'),
        ),
    ]
