# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-12 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0026_taskpackageowner_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpackage',
            name='isoverdue',
            field=models.NullBooleanField(default=False, verbose_name='\u8d85\u671f\u63d0\u9192'),
        ),
    ]
