# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-12 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0027_taskpackage_isoverdue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskpackageowner',
            old_name='overdue',
            new_name='isoverdue',
        ),
    ]
