# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0028_auto_20190312_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpackageowner',
            name='isoverdue',
            field=models.NullBooleanField(default=False, verbose_name='\u662f\u5426\u8d85\u671f'),
        ),
    ]
