# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-17 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskpackages', '0029_auto_20190314_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiontask',
            name='rgssde',
        ),
        migrations.AddField(
            model_name='regiontask',
            name='gbrgssde',
            field=models.CharField(max_length=1000, null=True, verbose_name='gbrgssde'),
        ),
        migrations.AddField(
            model_name='regiontask',
            name='jbrgssde',
            field=models.CharField(max_length=1000, null=True, verbose_name='jbrgssde'),
        ),
    ]
